

# import time
# from selenium import webdriver
# from selenium.webdriver.common.by import By
# from selenium.webdriver.support.select import Select
# driver = webdriver.Chrome()
# driver.implicitly_wait(10)
#
# class Facebook_signup:
#     def fbsignup(self):
#         driver.get("https://www.facebook.com/")
#         driver.maximize_window()
#         time.sleep(2)
#         driver.find_element(By.LINK_TEXT,"Create new account").click()
#         driver.find_element(By.NAME, "firstname").click()
#         driver.find_element(By.NAME, "firstname").send_keys("iron")
#         driver.find_element(By.NAME, "lastname").click()
#         driver.find_element(By.NAME, "lastname").send_keys("man")
#         time.sleep(1)
#         driver.find_element(By.NAME, "reg_email__").click()
#         driver.find_element(By.NAME, "reg_email__").send_keys("ironman@email.com")
#         time.sleep(1)
#         driver.find_element(By.NAME, "reg_email_confirmation__").is_displayed()
#         driver.find_element(By.NAME, "reg_email_confirmation__").click()
#         driver.find_element(By.NAME, "reg_email_confirmation__").send_keys("ironman@email.com")
#         time.sleep(2)
#         driver.find_element(By.NAME, "reg_email_confirmation__").is_displayed()
#         driver.find_element(By.NAME, "reg_email_confirmation__").click()
#         driver.find_element(By.NAME, "reg_email_confirmation__").clear()
#         time.sleep(2)
#         driver.find_element(By.NAME, "reg_email__").click()
#         driver.find_element(By.NAME, "reg_email__").clear()
#         time.sleep(2)
#         driver.find_element(By.NAME, "reg_email__").click()
#         driver.find_element(By.NAME, "reg_email__").send_keys(987654321)
#         time.sleep(2)
#         driver.find_element(By.NAME, "reg_passwd__").click()
#         driver.find_element(By.NAME, "reg_passwd__").send_keys("loveyou3000")
#         time.sleep(2)
#         dd = driver.find_element(By.XPATH,"//select[@id='day']")
#         dd1 = Select(dd)
#         dd1.select_by_value("1")
#         time.sleep(2)
#         dd1.select_by_value('25')
#         time.sleep(1)
#         driver.find_element(By.ID, "month").click()
#         driver.find_element(By.ID, "month").send_keys("jun")
#         time.sleep(2)
#         driver.find_element(By.ID, "year").click()
#         driver.find_element(By.ID, "year").send_keys("2000")
#         time.sleep(2)
#         driver.find_element(By.XPATH, "//label[normalize-space()='Female']").click()
#         time.sleep(2)
#         driver.find_element(By.XPATH, "//label[normalize-space()='Custom']").click()
#         time.sleep(1)
#         driver.find_element(By.XPATH, "//label[normalize-space()='Male']").click()
#         time.sleep(2)
#         print(driver.find_element(By.XPATH, "//label[normalize-space()='Custom']").is_displayed())
#         time.sleep(2)
#         print(driver.find_element(By.XPATH, "//label[normalize-space()='Custom']").is_selected())
#         driver.find_element(By.NAME, "websubmit").click()
#         time.sleep(2)
#         driver.close()
#
# fbobject = Facebook_signup()
# fbobject.fbsignup()